defaults: &defaults
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

development:
  bucket: facetskids
  <<: *defaults

test:
  bucket: facetskids-test
  <<: *defaults

production:
  bucket: facetskids
  <<: *defaults
